
-- Top 50 most popular brands on twitter on March 7 2011. 
-- Source: http://tweetedbrands.com/

INSERT INTO "Brands" ("brandName") VALUES ('Twitter');
INSERT INTO "Brands" ("brandName") VALUES ('Youtube');
INSERT INTO "Brands" ("brandName") VALUES ('Facebook');
INSERT INTO "Brands" ("brandName") VALUES ('iPhone');
INSERT INTO "Brands" ("brandName") VALUES ('Google');
INSERT INTO "Brands" ("brandName") VALUES ('Apple');
INSERT INTO "Brands" ("brandName") VALUES ('Android');
INSERT INTO "Brands" ("brandName") VALUES ('Blackberry');
INSERT INTO "Brands" ("brandName") VALUES ('Myspace');
INSERT INTO "Brands" ("brandName") VALUES ('Amazon');
INSERT INTO "Brands" ("brandName") VALUES ('BBC');
INSERT INTO "Brands" ("brandName") VALUES ('Nokia');
INSERT INTO "Brands" ("brandName") VALUES ('MTV');
INSERT INTO "Brands" ("brandName") VALUES ('CNN');
INSERT INTO "Brands" ("brandName") VALUES ('Microsoft');
INSERT INTO "Brands" ("brandName") VALUES ('Starbucks');
INSERT INTO "Brands" ("brandName") VALUES ('Yahoo!');
INSERT INTO "Brands" ("brandName") VALUES ('eBay');
INSERT INTO "Brands" ("brandName") VALUES ('Nike');
INSERT INTO "Brands" ("brandName") VALUES ('Disney');
INSERT INTO "Brands" ("brandName") VALUES ('Sony');
INSERT INTO "Brands" ("brandName") VALUES ('Mashable');
INSERT INTO "Brands" ("brandName") VALUES ('Samsung');
INSERT INTO "Brands" ("brandName") VALUES ('BP');
INSERT INTO "Brands" ("brandName") VALUES ('Ford');
INSERT INTO "Brands" ("brandName") VALUES ('Canon');
INSERT INTO "Brands" ("brandName") VALUES ('Motorola');
INSERT INTO "Brands" ("brandName") VALUES ('Guardian');
INSERT INTO "Brands" ("brandName") VALUES ('KFC');
INSERT INTO "Brands" ("brandName") VALUES ('Toyota');
INSERT INTO "Brands" ("brandName") VALUES ('Techcrunch');
INSERT INTO "Brands" ("brandName") VALUES ('Coca-Cola');
INSERT INTO "Brands" ("brandName") VALUES ('Dell');
INSERT INTO "Brands" ("brandName") VALUES ('Gucci');
INSERT INTO "Brands" ("brandName") VALUES ('BMW');
INSERT INTO "Brands" ("brandName") VALUES ('British Airways');
INSERT INTO "Brands" ("brandName") VALUES ('Pepsi');
INSERT INTO "Brands" ("brandName") VALUES ('Intel');
INSERT INTO "Brands" ("brandName") VALUES ('McDonald');
INSERT INTO "Brands" ("brandName") VALUES ('Honda');
INSERT INTO "Brands" ("brandName") VALUES ('Adidas');
INSERT INTO "Brands" ("brandName") VALUES ('IBM');
INSERT INTO "Brands" ("brandName") VALUES ('Panasonic');
INSERT INTO "Brands" ("brandName") VALUES ('T-Mobile');
INSERT INTO "Brands" ("brandName") VALUES ('Spotify');
INSERT INTO "Brands" ("brandName") VALUES ('Lego');
INSERT INTO "Brands" ("brandName") VALUES ('Digg');
INSERT INTO "Brands" ("brandName") VALUES ('Mercedes');
INSERT INTO "Brands" ("brandName") VALUES ('IKEA');
INSERT INTO "Brands" ("brandName") VALUES ('VW');
